# cli_golden.cmake — run the built CLI on examples/sample-input.json and compare
# stdout against the committed golden examples/sample-output.json.
#
# This proves the JSON plumbing (parse -> ts_triangulate -> render) is stable. It
# does NOT re-prove the math — that is the parity suite's job. The golden was
# generated by running this same CLI (the lib is parity-proven), so a diff here
# means the CLI's input/output behavior changed.
#
# Invoked via: cmake -DCLI=<path> -DIN=<path> -DEXP=<path> -P cli_golden.cmake

if(NOT DEFINED CLI OR NOT DEFINED IN OR NOT DEFINED EXP)
  message(FATAL_ERROR "cli_golden.cmake requires -DCLI=, -DIN=, -DEXP=")
endif()

execute_process(
  COMMAND "${CLI}"
  INPUT_FILE "${IN}"
  OUTPUT_VARIABLE actual
  RESULT_VARIABLE rc
)

if(NOT rc EQUAL 0)
  message(FATAL_ERROR "cli_golden: CLI exited non-zero (${rc})")
endif()

file(READ "${EXP}" expected)

if(NOT actual STREQUAL expected)
  message(FATAL_ERROR
    "cli_golden: CLI output does NOT match golden ${EXP}\n"
    "---- expected ----\n${expected}\n"
    "---- actual ----\n${actual}\n")
endif()

message(STATUS "cli_golden: CLI output matches golden")
